MASEmployeeApplication/Models/AbstractEmployee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MASEmployeeApplication.Models
{
    public abstract class AbstractEmployee
    {
        public abstract void CalculateAnnualSalary();

        private int id;
        private String name;
        private int roleId;
        private String roleName;
        private String roleDescription;
        private double hourlySalary;
        private double monthlySalary;

        public int Id { get => id; set => id = value; }
        public string Name { get => name; set => name = value; }
        public int RoleId { get => roleId; set => roleId = value; }
        public string RoleName { get => roleName; set => roleName = value; }
        public string RoleDescription { get => roleDescription; set => roleDescription = value; }
        public double HourlySalary { get => hourlySalary; set => hourlySalary = value; }
        public double MonthlySalary { get => monthlySalary; set => monthlySalary = value; }

    }
}

MASEmployeeApplication/Models/EmployeeFactory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MASEmployeeApplication.Models
{
    public class EmployeeFactory
    {
        public AbstractEmployee BuildEmployee(RawEmployee employee)
        {

            AbstractEmployee newEmployee = GetEmployeePerContractType(employee);

            newEmployee.Id = employee.Id;
            newEmployee.Name = employee.Name;
            newEmployee.RoleId = employee.RoleId;
            newEmployee.RoleName = employee.RoleName;
            newEmployee.RoleDescription = employee.RoleDescription;
            newEmployee.HourlySalary = employee.HourlySalary;
            newEmployee.MonthlySalary = employee.MonthlySalary;

            newEmployee.CalculateAnnualSalary();
            return newEmployee;
        }

        private AbstractEmployee GetEmployeePerContractType(RawEmployee employee)
        {
            switch (employee.ContractTypeName)
            {
                case "HourlySalaryEmployee":
                    return new HourlySalaryEmployee();
                case "MonthlySalaryEmployee":
                    return new MonthlySalaryEmployee();
                default:
                    throw new InvalidOperationException("Cannot create an object of this contract type");
            }
        }
    }
}

MASEmployeeApplication/Models/HourlySalaryEmployee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MASEmployeeApplication.Models
{
    public class HourlySalaryEmployee : AbstractEmployee
    {
        private double annualSalary;
        private String contractType = "Hourly";
        public double AnnualSalary { get => annualSalary; set => annualSalary = value; }
        public String ContractType { get => contractType; }


        public override void CalculateAnnualSalary()
        {
            AnnualSalary = 120 * this.HourlySalary * 12;
        }
    }
}

MASEmployeeApplication/Models/HttpEmployeeClient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace MASEmployeeApplication.Models
{
    public class HttpEmployeeClient
    {
        private HttpClient client = new HttpClient();

        public HttpEmployeeClient()
        {
            client.BaseAddress = new Uri("http://masglobaltestapi.azurewebsites.net");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json")
            );
        }

        public async Task<String> GetEmployees()
        {
            HttpResponseMessage response = await client.GetAsync("/api/Employees");

            Task<string> t = null;

            if (response.IsSuccessStatusCode)
            {
                t = response.Content.ReadAsStringAsync();
            }

            return await t;
        }

    }
}

MASEmployeeApplication/Models/MonthlySalaryEmployee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MASEmployeeApplication.Models
{
    public class MonthlySalaryEmployee : AbstractEmployee
    {
        private double annualSalary;
        private String contractType = "Monthly";
        public double AnnualSalary { get => annualSalary; set => annualSalary = value; }
        public String ContractType { get => contractType; }

        public override void CalculateAnnualSalary()
        {
            AnnualSalary =  MonthlySalary * 12;
        }
    }
}

MASEmployeeApplication/Models/RawEmployee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MASEmployeeApplication.Models
{
    public class RawEmployee : AbstractEmployee
    {
        private String contractTypeName;
        public string ContractTypeName { get => contractTypeName; set => contractTypeName = value; }

        public override void CalculateAnnualSalary()
        {
            throw new NotImplementedException("This method is not available for this type of employee");
        }
    }
}

MASEmployeeApplication/Controllers/EmployeeDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MASEmployeeApplication.Controllers
{
    public class EmployeeDetailsController : Controller
    {
        // GET: EmployeeDetails
        public ActionResult Index()
        {
            ViewBag.Title = "Employee Details";
            return View();
        }
    }
}

MASEmployeeApplication/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MASEmployeeApplication.Models;

namespace MASEmployeeApplication.Controllers
{
    public class EmployeesController : ApiController
    {
        private HttpEmployeeClient client;
        private EmployeeFactory factory;
        public EmployeesController()
        {
            client = new HttpEmployeeClient();
            factory = new EmployeeFactory();
        }

        // GET: api/Employees
        public async Task<String> Get()
        {
            string employeesJson = await client.GetEmployees();
            List<AbstractEmployee> employees = new List<AbstractEmployee>();

            List<RawEmployee> rawEmployees = JsonConvert.DeserializeObject<List<RawEmployee>>(employeesJson);

            foreach (RawEmployee rawEmployee in rawEmployees)
            {
                AbstractEmployee employee = factory.BuildEmployee(rawEmployee);

                employees.Add(employee);

            }

            return JsonConvert.SerializeObject(employees);
        }

        // GET: api/Employees/5
        public async Task<String> Get(int id)
        {
            string employeesJson = await client.GetEmployees();
            List<AbstractEmployee> employees = new List<AbstractEmployee>();

            List<RawEmployee> rawEmployees = JsonConvert.DeserializeObject<List<RawEmployee>>(employeesJson);

            RawEmployee rawEmployee = (from rawEmp in rawEmployees where rawEmp.Id == id select rawEmp).FirstOrDefault();

            if (rawEmployee != null)
            {
                AbstractEmployee employee = factory.BuildEmployee(rawEmployee);
                employees.Add(employee);
            }
            return JsonConvert.SerializeObject(employees);

        }

        // POST: api/Employees
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/Employees/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/Employees/5
        public void Delete(int id)
        {
        }
    }
}

MASEmployeeApplication/Views/EmployeeDetails/Index.cshtml
    <h1>Employee Details</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <table id="employee-details-table" width="700">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Role Name</th>
                            <th>Role Description</th>
                            <th>Contract Type</th>
                            <th>Annual Salary</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="col-md-4">
                <form id="employee-details-form">
                    <div class="form-group">
                        <input type="text" id="employee-id" placeholder="User Id"/>
                    </div>
                    <a href="#" id="get-employee-details" class="btn btn-primary"><span class="glyphicon glyphicon-user"></span>Get Users</a>
                </form>
                
            </div>
        </div>
    </div>

<script>
    $(document).ready(function () {
        $employeeId = $("#employee-id");
        $employeeDetailsBtn = $("#get-employee-details");
        $employeeDetailsTable = $("#employee-details-table");
        $employeeDetailsBtn.on("click", function (e) {
            e.preventDefault();
            var employeeId = $employeeId.val();

            if (isNaN(employeeId) || !Number.isInteger(+employeeId)) {
                alert("Please only enter integers on this field");
                $employeeId.val('');
                return;
            }

            var url = "/api/Employees/";

            if (employeeId) {
                url += employeeId;
            }

            $.ajax({
                url: url,
                dataType: "JSON",
                method: "GET",
                success: function (response) {
                    var data = JSON.parse(response);
                    console.log(data);
                    $employeeDetailsTable.DataTable({
                        destroy: true,
                        data: data,
                        columns: [
                            { data: "Id" },
                            { data: "Name" },
                            { data: "RoleName" },
                            { data: "RoleDescription" },
                            { data: "ContractType" },
                            { data: "AnnualSalary", render: $.fn.dataTable.render.number(',', '.', 2, '$') }
                        ],
                        searching: false,
                        ordering: false,
                        paging: false
                    });
                }
            });

            
        });
    });
</script>

MASEmployeeApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MAS Employee Details", "Index", "EmployeeDetails", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "EmployeeDetails", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>